version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: cheque_especial_mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: cheque_especial
      MYSQL_USER: app_user
      MYSQL_PASSWORD: app_password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - cheque_especial_network

  app:
    build: .
    container_name: cheque_especial_app
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_NAME=cheque_especial
      - DB_USER=root
      - DB_PASSWORD=rootpassword
    depends_on:
      - mysql
    volumes:
      - .:/app
      - /app/node_modules
    networks:
      - cheque_especial_network
    command: npm start

volumes:
  mysql_data:

networks:
  cheque_especial_network:
    driver: bridge

